---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}-registry
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
    name: {{ include "bailo.fullname" . }}-registry
spec:
  ports:
    - port: {{ .Values.registry.port }}
      targetPort: {{ .Values.registry.port }}
      protocol: TCP
      name: tcp
  selector:
    name: {{ include "bailo.fullname" . }}-registry
