---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}-nginx
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  selector:
    name: {{ include "bailo.fullname" . }}-nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginxAuth.port }}
      targetPort: http