apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bailo.fullname" . }}
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
data:
  production.js: |
    module.exports = {
      minio: {
        endPoint: '{{ include "bailo.minio.host" . }}',
        port: {{ .Values.minio.service.ports.api }},
        useSSL: false,
        region: '',
        uploadBucket: '{{ .Values.minio.uploadBucket }}',
        registryBucket: '{{ .Values.minio.registryBucket }}',
      },
    
      registry: {
        host: '{{ .Values.registry.host }}:{{ .Values.registry.port }}',
        insecure: {{ .Values.registry.insecure }},
      },
      redis: {
          host: '{{ include "bailo.redis.host" . }}',
      },
      mongo: {
          uri: `mongodb://mongodb:${process.env.MONGO_PASSWORD}@{{ include "bailo.mongo.host" . }}:{{ .Values.mongodb.service.port }}/{{ .Values.mongodb.collectionName }}`,
      }
    }
  custom-environment-variables.js: |
    module.exports = {
      minio: {
          accessKey: 'MINIO_ACCESS_KEY',
          secretKey: 'MINIO_SECRET_KEY',
      },
      redis: {
        password: 'REDIS_PASSWORD',
      }
    }
