apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bailo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    name: registry
spec:
  ports:
    - port: {{ .Values.registry.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.registry.host }}
--- 
apiVersion: v1
kind: Service
metadata:
  name: smtp
  labels:
    name: smtp
spec:
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.smtp.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    name: {{ .Values.smtp.host }}