apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bailo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    name: registry
spec:
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: registry
--- 
apiVersion: v1
kind: Service
metadata:
  name: maildev
  labels:
    name: maildev
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    name: maildev