---
apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nginxAuth.port }}
      targetPort: {{ .Values.nginxAuth.port }}
  selector:
    name: {{ .Values.nginxAuth.host }}
