# Default values for bailo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bailo
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets: []

podAnnotations: {}

# Instance scaling
# ReplicateCount ignored if autoscaling is enabled
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


# Pod Security
podSecurityContext: {}
  # fsGroup: 2000
securityContext:
  # capabilities:
  #   drop:
  #     - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  # runAsUser: 1002380001

# Networking
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: "true|false"
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 400m
    memory: 800Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Pod placement
nodeSelector: {}
tolerations: []
affinity: {}

# Application Dependencies
mongodb:
  enabled: true
  auth:
    enabled: true
    rootUser: ""
    rootPassword: ""
    existingSecret: "bailo-mongodb"
    usernames: [ bailo_user ]
    passwords: [ ]
    databases: [ bailo ]
  service:
    port: 31110 #27017./config/default.js:21 host: 'localhost:8080'
  collectionName: bailo #db used by bailo during connecting to mongo
  persistence:
    size: 10Gi
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: 4.4.13-debian-10-r0
  #password: 'SetYouPasswordInLocal.yaml'
  #host: 'SetYouPasswordInLocal.yaml'

minio:
  enabled: true
  auth:
    rootUser: ""
    rootPassword: ""
    existingSecret: "bailo-minio"
  defaultBuckets: "uploads,registry"
  uploadBucket: uploads
  registryBucket: registry
  host: "bailo-minio"
  service:
    ports:
      api: 31111 #9000
  useSSL: false
  persistence:
    size: 10Gi
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  image:
    registry: docker.io
    repository: bitnami/minio
    tag: 2022.2.12-debian-10-r0
    debug: true

registry:
  repository: registry
  tag: 2
  enabled: true
  host: "registy"
  port: 31113 #5000
  insecure: true
  certDir: "/certs"
  certFile: "yourcert.pem"
  keyFile: "yourkey.pem"

nginxAuth:
  repository: nginxinc/nginx-unprivileged
  tag: latest
  host: "bailo-nginx-auth-proxy"
  #port: 8443
  port: 8080
  #certDir: "/certs"
  #certFile: "tls.crt"
  #keyFile: "tls.key"

openshift:
  namespace: bailo
  appPublicRoute: 'openshift-route-url'
  dockerPushSecretName: 'registry-push-secret'

# Instance Settings
config:
  s2i:
    image: seldonio/seldon-core-s2i-python37:1.10.0
  supportEmail: "support@example.com"
  documentationLink: "https://example.com/support"

  ui:
    banner:
      text: "Banner Text Here"
      colour: '#00CC00'

  smtp:
    host: 'example.com'
    from: 'bailo@example.com'

  schema:
    script: 'schema-setup-script.sh'


# nginx.deployment registry.deployment
nginxcert:
  cert: "cert.pem"
  key: "key.pem"
