# Default values for bailo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bailo
  tag: "0.1.0"
  pullPolicy: Always
imagePullSecrets: []

podAnnotations: 
  container.apparmor.security.beta.kubernetes.io/bailo: unconfined
  container.seccomp.security.alpha.kubernetes.io/bailo: unconfined

# Instance scaling
# ReplicateCount ignored if autoscaling is enabled
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


# Pod Security
podSecurityContext: {}
  # fsGroup: 2000
securityContext:
  # capabilities:
  #   drop:
  #     - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

# Networking
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: #{}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
   requests:
     ephemeral-storage: "2Gi"
  #   cpu: 100m
  #   memory: 128Mi


# Pod placement
nodeSelector: {}
tolerations: []
affinity: {}

# Application Dependencies
mongodb:
  enabled: true
  auth:
    enabled: true
    rootUser: ""
    rootPassword: ""
    existingSecret: "bailo-mongodb"
    usernames:
      - mongodb
    passwords: []
    databases:
      - bailo
  service:
    port: 27017
  host: ""
  collectionName: bailo
    
minio:
  enabled: true
  auth:
    rootUser: "minioadmin"
    rootPassword: "minioadmin"
    existingSecret: "bailo-minio"
  defaultBuckets: "uploads,registry"
  uploadBucket: uploads
  registryBucket: registry
  host: ""
  service:
    ports:
      api: 9000
  useSSL: false

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: ""
    existingSecret: "bailo-redis"
    existingSecretPasswordKey: "redis-password"
  host: ""
  master:
    service:
      port: 6379
  replica:
    replicaCount: 0
  
registry:
  enabled: true
  host: "registry"
  port: 5000
  insecure: true

smtp:
  host: "maildev"
  port: 25
  insecure: true