---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bailo.fullname" . }}-config
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
data:
  production.js: |
    module.exports = {
      minio: {
        endPoint: '{{ include "bailo.minio.host" .}}',
        port: {{ .Values.minio.service.ports.api }},
        useSSL: {{ .Values.minio.useSSL }},
        region: '',
        uploadBucket: '{{ .Values.minio.uploadBucket }}',
        registryBucket: '{{ .Values.minio.registryBucket }}',
        createBuckets: false,
      },
      smtp: {
        host: '{{ .Values.config.smtp.host }}',
        port: 1025,
        secure: false,
        auth: { user: 'mailuser', pass: 'mailpass' },
        tls: { rejectUnauthorized: false },
        from: '{{ .Values.config.smtp.from }}',
      },
      openshift: {
        namespace: '{{ .Values.openshift.namespace }}',
        appPublicRoute: '{{ .Values.openshift.appPublicRoute }}',
        dockerPushSecretName: '{{ .Values.openshift.dockerPushSecretName }}',
      },
      s2i: {
        builderImage: '{{ .Values.config.s2i.image }}',
      },
      uiConfig: {
        banner: {
          enable: true,
          text: '{{ .Values.config.ui.banner.text }}',
          colour: '{{ .Values.config.ui.banner.colour }}',
        },
        issues: {
          label: 'Bailo Support Team',
          supportHref: 'mailto:{{ .Values.config.supportEmail }}?subject=Bailo%20Support',
          contactHref: 'mailto:{{ .Values.config.supportEmail }}?subject=Bailo%20Contact',
        },
        help: {
          documentationUrl: '{{ .Values.config.documentationLink }}',
        },
        registry: {
          host: '{{ .Values.openshift.appPublicRoute }}',
        },
      },
      mongo: {
        uri: 'mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.host }}',
        connectionOptions: {
          useFindAndModify: false,
          useNewUrlParser: true,
          useUnifiedTopology: true,
          useCreateIndex: true,
          //ssl: false,
          //sslValidate: false,
        },
      }
    }
  custom-environment-variables.js: |
    module.exports = {
      minio: {
        accessKey: 'MINIO_ACCESS_KEY',
        secretKey: 'MINIO_SECRET_KEY',
      },
    }
