---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bailo-test-eks
  region: eu-west-2

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: bailo-test-node
    instanceType: t3.medium
    minSize: 1
    maxSize: 2
