{{- if .Values.maildev.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bailo.fullname" . }}-maildev
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bailo.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bailo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: maildev
        image: maildev/maildev:2.0.2
        args: ["-s", "{{ .Values.config.smtp.port }}", "-w", "1080"]
        env:
        - name: MAILDEV_INCOMING_USER
          value: {{ .Values.config.smtp.user }}
        - name: MAILDEV_INCOMING_PASS
          value: {{ .Values.config.smtp.pass }}
{{- end }}
