---
apiVersion: v1
kind: Service
metadata:
  name: mail
  labels:
    name: mail
spec:
  ports:
    - port: 1080
      targetPort: 1080
      protocol: TCP
      name: http
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
  selector:
    name: maildev
