---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: maildev
  template:
    metadata:
      labels:
        name: maildev
    spec:
      containers:
      - name: maildev
        image: maildev/maildev:2.0.2
        args: ["-s", "1025", "-w", "1080"]
        env:
        - name: MAILDEV_INCOMING_USER
          value: mailuser
        - name: MAILDEV_INCOMING_PASS
          value: mailpass
