name: Build Bailo Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Clone repository
      - uses: actions/checkout@v2

      # Setup BuildX
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build production image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.prod
          tags: bailo:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect Bailo image
        run: docker image inspect bailo:latest
