name: Build Bailo Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_image:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Clone repository
      - uses: actions/checkout@v2

      # Setup BuildX
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build production image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.prod
          tags: bailo:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect Bailo image
        run: docker image inspect bailo:latest

  unit_testing:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      # Create certs
      - run: sudo chown -R runner:docker certs
      - run: npm run certs

      # Install dependencies
      - run: npm ci

      # Run unit tests
      - run: npm run test
