name: MiniKube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: mkdir logs

    # Install dependencies
    - run: npm ci

    # Create certs
    - run: sudo chown -R runner:docker certs
    - run: npm run certs
    
    # copy cert to helm
    - name: Copy certs to helm
      run: sudo cp certs/*.pem helm/bailo/certs/.
    
    - name: Start minikube
      uses: medyagh/setup-minikube@master
      
    - name: List cluster
      run: kubectl get pods -A
      
    - name: Build image
      #working-directory: Bailo
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile.prod -t bailo .
        echo -n "verifying images:"
        docker images        
#    - name: Deploy to minikube
#      run:
#        kubectl apply -f deploy-to-minikube.yaml
#    - name: Test service URLs
#      run: |
#        minikube service list
#        minikube service example --url
#        echo "------------------opening the service------------------"
#        curl $(minikube service example --url)
