name: MiniKube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: mkdir logs

      # Install dependencies
      - run: npm ci

      # Create certs
      - run: sudo chown -R runner:docker certs
      - run: npm run certs

      # remove route set for openshift
      - name: remove route config
        run: sudo rm helm/bailo/templates/route.yaml

      # Create local.yaml
      - name: Create local.yaml
        run: |
          cat << EOT >> helm/bailo/local.yaml
          ---
          # Instance Settings
          config:
            s2i:
              image: seldonio/seldon-core-s2i-python37:1.10.0
            supportEmail: "support@example.com"
            documentationLink: "https://example.com/support"

            ui:
              banner:
                text: "BAILO"
                colour: '#047a06'

            smtp:
              host: 'mail'
              from: 'bailo@example.com'

            schema:
              script: "dist/server/scripts/exampleSetAllSchemas.js"

          # Bailo
          image:
            repository: "local/bailo"
            tag: "latest"

          # Used for k8s not openshift
          ingress:
            enabled: false

          mongodb:
            auth:
              passwords:
                - MongoDBPassword
              usernames:
                - bailo_user
            image:
              registry: docker.io
            host: 'bailo-mongodb.yetToConfirm:31110/bailo'

          minio:
            image:
              registry: docker.io
            persistence:
              size: 20Gi

          registry:
            repository: registry
            certFile: cert.pem
            keyFile: key.pem

          maildev:
            enabled: true

          nginxcert:
            cert: cert.pem
            key: key.pem
          EOT

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: List cluster
        run: kubectl get pods -A

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile.prod -t local/bailo .
          echo -n "verifying images:"
          docker images
          
      - name: HELM update depency update
        run: current_dir=$PWD;cd helm/bailo/;helm dependency update;cd $current_dir;
        
#    - name: Deploy to minikube
#      run:
#        kubectl apply -f deploy-to-minikube.yaml
#    - name: Test service URLs
#      run: |
#        minikube service list
#        minikube service example --url
#        echo "------------------opening the service------------------"
#        curl $(minikube service example --url)
