name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Initial setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Linting
      - run: npm run check-style
      - run: npm run lint

      # Build image
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: .next
          key: ${{ runner.os }}-next
          restore-keys: |
            ${{ runner.os }}-next

      # Setup dependencies
      - name: Build the stack
        run: docker-compose up -d

      # Add configuration
      - shell: bash
        run: |
          cat <<EOT >> config/local.js
          module.exports = {
            minio: {
              accessKey: 'minioadmin',
              secretKey: 'minioadmin',
            },

            smtp: {
              auth: {
                user: 'mailuser',
                pass: 'mailpass',
              },
              tls: {
                rejectUnauthorized: false,
              },
            }
          }
          EOT

      # Setup app
      - name: Setup app
        run: |
          sudo chown -R runner:docker certs
          npm run certs

          npm i -g ts-node
          ts-node --project tsconfig.server.json server/scripts/addDeploymentSchema.ts
          ts-node --project tsconfig.server.json server/scripts/addUploadSchema.ts

      # Start app and wait for it to start
      - run: npm start &
      - uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:8080/'
          responseCode: '200'
          timeout: 10000
          interval: 500

      # Run tests
      - run: HEADLESS=true npm test -- -t "renders a heading"
