name: Build / Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Initial setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: mkdir logs

      # Install dependencies
      - run: npm ci

      # Linting
      - run: npm run check-style
      - run: npm run lint

      # Setup dependencies
      
      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - run: docker-compose pull

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build the stack
        run: |
          sudo chown -R runner:docker certs
          npm run certs
          cat <<EOT >> config/local.js
          module.exports = {
            minio: {
              accessKey: 'minioadmin',
              secretKey: 'minioadmin',
            },

            smtp: {
              auth: {
                user: 'mailuser',
                pass: 'mailpass',
              },
              tls: {
                rejectUnauthorized: false,
              },
            },

          }
          EOT

          docker-compose up --force-recreate --build -d

      # wait for app to start
      - run: |
          chmod +x ./server/scripts/waitForIt.sh
          ./server/scripts/waitForIt.sh localhost:8080 -t 10

      # Run tests
      - run: HEADLESS=true npm test

      - name: Dump docker-compose logs
        if: always()
        run: docker-compose logs > logs/stack.log

      - name: Docker Compose Logs
        if: always()
        run: cat logs/stack.log

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: logs
