name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Initial setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Linting
      - run: npm run check-style
      - run: npm run lint

      # Build image
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: ~/.next
          key: ${{ runner.os }}-next
          restore-keys: |
            ${{ runner.os }}-next

      # Setup dependencies
      - name: Build the stack
        run: docker-compose up -d

      # Setup app
      - name: Setup app
        run: |
          npm run certs
          npm i -g ts-node
          ts-node --project tsconfig.server.json server/scripts/addDeploymentSchema.ts
          ts-node --project tsconfig.server.json server/scripts/addUploadSchema.ts

      # Start app and wait for it to start
      - run: npm start &
      - name: Wait for app to start
        run: docker run appropriate/curl -s --connect-timeout 5 --max-time 5 --retry 10 --retry-delay 0 --retry-max-time 50 --retry-connrefused http://localhost:8080/

      # Run tests
      - run: HEADLESS=true npm test -- -t "renders a heading"
