name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Initial setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Linting
      - run: npm run check-style
      - run: npm run lint

      # Build image
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: ~/.next
          key: ${{ runner.os }}-next
          restore-keys: |
            ${{ runner.os }}-next

      # Setup dependencies
      - name: Build the stack
        run: docker-compose up -d

      # Start app
      - name: Run tests
        # Run using screen, otherwise we can't kill app.
        run: |
          screen -d -m npm start
          npm test
          kill -9 `top -n 1 | pgrep screen`
