name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Initial setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Linting
      - run: npm run check-style
      - run: npm run lint

      # Build image
      - run: npm run build
      - uses: actions/cache@v2
        with:
          path: ~/.next
          key: ${{ runner.os }}-next
          restore-keys: |
            ${{ runner.os }}-next

      # Setup dependencies
      - name: Build the stack
        run: docker-compose up -d

      # Start app and wait for it to start
      - run: npm start &
      - name: Wait for app to start
        run: docker run appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/

      # Run tests
      - run: npm test
