name: Python Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.12']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          cd lib/python-beta
          python -m pip install -e .[test]

      # Black
      - name: Check formatting
        run: |
          cd lib/python-beta
          black --check --verbose .

      # Pylint
      - name: Check linting
        run: |
          cd lib/python-beta
          pylint src/bailo --verbose --exit-zero --fail-on=F,E

      # Pytest
      - name: Run basic testing
        run: |
          cd lib/python-beta
          python -m pytest
